"""changed chatroom name to be unique

Revision ID: 3988d5563e5f
Revises: bccc105ace0b
Create Date: 2020-04-24 11:02:26.611932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3988d5563e5f'
down_revision = 'bccc105ace0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chatroom', ['chatroom_name'])
    op.create_foreign_key(None, 'message', 'chatroom', ['chatroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'chatroom', type_='unique')
    # ### end Alembic commands ###
