"""chatroom table

Revision ID: bccc105ace0b
Revises: 49e8fc8914d6
Create Date: 2020-04-24 10:24:12.274731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccc105ace0b'
down_revision = '49e8fc8914d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chatroom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'chatroom', ['chatroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'chatroom_id')
    # ### end Alembic commands ###
